
FROM ubuntu:16.04 AS build

ARG PYTHON_VERSION=2.7
ARG CONDA_PYTHON_VERSION=2
ARG CONDA_DIR=/opt/conda

# Instal basic utilities
RUN apt-get update && \
    apt-get install -y --no-install-recommends git wget unzip bzip2 build-essential ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV PATH $CONDA_DIR/bin:$PATH
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda$CONDA_PYTHON_VERSION-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    echo 'export PATH=$CONDA_DIR/bin:$PATH' > /etc/profile.d/conda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    rm -rf /tmp/* && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN conda install -c r r-randomforest
RUN conda install -c r r-caret

RUN conda update conda 
RUN conda install -c anaconda matplotlib
RUN conda install -c anaconda pandas=0.24.2

RUN conda install python=3
RUN conda install -c bioconda -c conda-forge snakemake

RUN git clone https://github.com/jaidevjoshi83/Final_hydro.git
RUN chmod +x /Final_hydro/bin/by_event_for_model_NEW.py
RUN chmod +x /Final_hydro/bin/make_dly_obs_table_standalone_NEW.py
RUN chmod +x /Final_hydro/bin/model_flood_counts_rf_ps_cln_NEW.r
RUN chmod +x /Final_hydro/bin/prepare_flood_events_table_NEW.py
RUN chmod +x /Final_hydro/Hydrology_WorkFlow.py

COPY hampt_rd_data.sqlite /Final_hydro/step2



